Migrate to Swift 5
mwoollard/SwiftGooglePolyline pull request #5
Opened 2022-06-10 16:26 UTC by sssbohdan

• Make code more modern-looking
• Fix formatting in a lot of places
• Remove unnecessary test extension

2022-06-10 16:27 UTC, sssbohdan commented
@mwoollard Can you please review when you have time, thanks

2022-06-11 18:32 UTC, mwoollard commented
@sssbohdan Thanks for taking the time to update this very old code! Swift 2 I think :-) I'll have a look over the w/e at the PR.

2022-06-12 06:25 UTC, mwoollard requested changes
Hi - just a few formatting issues (spacing next to parameter name) - if you can update for those will approve and merge. I'll then add SPM support !

Thanks again for your time and interest.
Best regards
Mark

2022-06-12 06:25 UTC, mwoollard commented on SwiftGooglePolyline/String+GooglePolyline.swift
> +  init<S: Sequence>(googlePolylineLocationCoordinateSequence sequence:S)
Add space sequence:S

2022-06-12 06:25 UTC, mwoollard commented on SwiftGooglePolyline/String+GooglePolyline.swift
> +    self.init(googlePolylineLocationCoordinateSequence:sequence.map { $0.coordinate })
Add space after :

2022-06-12 06:25 UTC, mwoollard commented on SwiftGooglePolyline/String+GooglePolyline.swift
> +    return MKPolyline(sequence:try self.makeCoordinateSequenceFromGooglePolyline())
Add space after :

2022-06-12 06:25 UTC, mwoollard commented on SwiftGooglePolyline/MKPolyline+GooglePolyline.swift
> +  public convenience init<S: Sequence>(sequence:S) where S.Iterator.Element == CLLocationCoordinate2D {
Add space sequence:S

2022-06-12 16:14 UTC, sssbohdan commented
> Hi - just a few formatting issues (spacing next to parameter name) - if you can update for those will approve and merge. I'll then add SPM support !
> 
> Thanks again for your time and interest. Best regards Mark

Thanks for the review and thanks for implementing the algorithm :)

2022-06-12 16:28 UTC, merged